name: Rust

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  build_and_release:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build for macOS
        run: |
          # rustup target add x86_64-apple-darwin
          # cargo build --release --target x86_64-apple-darwin

      - name: Get next version
        uses: reecetech/version-increment@2024.10.1
        id: version
        with:
          scheme: semver
          increment: patch

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/x86_64-apple-darwin/release/todo-app
          tag_name: ${{ steps.version.outputs.version }}
          name: Release ${{ steps.version.outputs.version }}
          draft: false
          prerelease: false
          body: "Content ${{ steps.version.outputs.version }}"
