name: Rust

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_release:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build for macOS
        run: |
          rustup target add x86_64-apple-darwin
          cargo build --release --target x86_64-apple-darwin

      - name: Generate release tag
        id: tag
        run: |
          sha=$(git rev-parse --short HEAD)
          timestamp=$(date +%Y%m%d_%H%M%S)
          echo "release_tag=release-${timestamp}-${sha}" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/x86_64-apple-darwin/release/todo-app
          name: Release ${{ steps.tag.outputs.release_tag }}
          tag_name: ${{ steps.tag.outputs.release_tag }}
          draft: false
          prerelease: false
