name: Rust

on:
  push:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build for macOS
        run: cargo build --target x86_64-apple-darwin --verbose

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4
      - name: Build for Windows
        run: cargo build --target x86_64-pc-windows-msvc --verbose
      - name: Upload macOS build
        uses: actions/upload-artifact@v3
        with:
          name: macos-build
          path: target/x86_64-apple-darwin/debug/
      - name: Upload Windows build
        uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: target/x86_64-pc-windows-msvc/debug/
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: latest
          release_name: Latest Release
          draft: false
          prerelease: false
      - name: Upload macOS to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/x86_64-apple-darwin/debug/
          asset_name: macos-build.zip
          asset_content_type: application/zip
      - name: Upload Windows to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/x86_64-pc-windows-msvc/debug/
          asset_name: windows-build.zip
          asset_content_type: application/zip
