name: Rust

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

# when implementing windows: https://dzfrias.dev/blog/deploy-rust-cross-platform-github-actions/

jobs:
  build_and_release:
    runs-on: macos-latest

    strategy:
      matrix:
        include:
          - build: macos
            os: macos-latest
            target: x86_64-apple-darwin

          # - build: windows-gnu
          #   os: windows-latest
          #   target: x86_64-pc-windows-gnu

    steps:
      - uses: actions/checkout@v4
      - name: Build for macOS
        run: |
          rustup target add x86_64-apple-darwin
          cargo build --release --target x86_64-apple-darwin

      - name: Get next version
        uses: reecetech/version-increment@2024.10.1
        id: version
        with:
          scheme: semver
          increment: patch

      - name: Build archive
        shell: bash
        run: |
          binary_name="todo-app"

          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            7z a "$binary_name-${{ steps.version.outputs.version }}-${{ matrix.target }}.zip" "target/${{ matrix.target }}/release/$binary_name.exe"
          else
            tar -czf "$binary_name-${{ steps.version.outputs.version }}-${{ matrix.target }}.tar.gz" "target/${{ matrix.target }}/release/$binary_name"
          fi
          echo "ASSET=$binary_name-${{ steps.version.outputs.version }}-${{ matrix.target }}.${{ matrix.os }}-latest.tar.gz" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.ASSET }}
          tag_name: ${{ steps.version.outputs.version }}
          name: Release ${{ steps.version.outputs.version }}
          draft: false
          prerelease: false
          body: "Content ${{ steps.version.outputs.version }}"
