name: Rust

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  build_and_release:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build for macOS
        run: |
          rustup target add x86_64-apple-darwin
          cargo build --release --target x86_64-apple-darwin

      - name: Extract Release Tag
        id: extract_tag
        run: |
          tag=${GITHUB_REF#refs/tags/}
          echo "release_tag=${tag}" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/x86_64-apple-darwin/release/todo-app
          name: ${{ steps.extract_tag.outputs.release_tag }}
          tag_name: ${{ steps.extract_tag.outputs.release_tag }}
          draft: false
          prerelease: false

      - name: Update Latest Tag
        run: |
          git tag -f latest
          git push origin -f latest
