name: Rust

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_release:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build for macOS
        run: |
          rustup target add x86_64-apple-darwin
          cargo build --release --target x86_64-apple-darwin

      - name: Create macOS Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/x86_64-apple-darwin/release/todo-app
          name: Release
          tag_name: latest
          draft: false
          prerelease: false
